### ISSUE TITLE
figure out if fetching module schemas from blue-build/modules is feasible

### ISSUE THREAD

**Issue by xynydev** [blue-build/schema#2]

**Comment by gmpinder** [comment]
So we could add schema definitions into labels for module images. Something like

```dockerfile
LABEL org.blue-build.module.${module_name}.schema="{ ... }"
```

Then the CLI can inspect the image and check for that to use it to validate the input.

**Comment by xynydev** [comment]
Yeah, that could work. This issue was more about fetching schemas from the module repo to this repo, but I think that can be done with `module.yml`.
